# MY NOTE: Auto-generated by the 'rolify' gem's generator
Rolify.configure do |config|
  # By default ORM adapter is ActiveRecord. Uncomment to use mongoid.
  # config.use_mongoid
  
  # Dynamic shortcuts for User class (user.is_admin? like methods). Is false by
  # default. Enable this feature AFTER running rake db:migrate, as it relies on
  # the roles table.
  # config.use_dynamic_shortcuts
end
