# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random, no regular
# words or you'll be exposed to dictionary attacks. You can use `rake secret` to
# generate a secure secret key.

# Make sure the secrets in this file are kept private if you're sharing your
# code publicly.

# MY NOTE: The 'defaults' section is added by us
defaults: &defaults
  twitter_consumer_key: 'H7KxTzrTAh41NT2OuF5LChYVK'
  twitter_consumer_secret: 'xIcrI497toRE7WVBS0MKpYnjYVhdvSpTR5TDeFbAiGnHVtl84x'
  twitter_access_token: '2731059560-izGpONMqZ0aVqoex8RIAPGy6TDAVLbtukcreBZm'
  twitter_access_token_secret: 'Qdehiila8IYLGuAZM2ScAQwxolvm53B4zdNNlZoCR7eI8'

development:
  secret_key_base: 20386981364ffde79760c1fbb2a7a0a6825666911881bbc0aeeda5a5863b1e9582839fc12972ce88cb169f1eeb04e4e89d0a3514d450a3ca97fc11c67da1416d
  # MY NOTE: All below added by us
  <<: *defaults

test:
  secret_key_base: 30c6bf96ac41b012f3eb9ead75d5dc779bc54febabb2d18897b0e6d5225ee3f5452f106cab2e954a1966789e3d69eda4058daf8db87db1b6ff8ef8cd66e2fca1
  # MY NOTE: All below added by us
  # MY NOTE: All below added by us
  <<: *defaults

# Do not keep production secrets in the repository, instead read values from the
# environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # MY NOTE: All below added by us
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  twitter_access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  twitter_access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
